version = 0.1

[default]
[default.global]
[default.global.parameters]
stack_name = "echo-api-prod"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
resolve_s3 = true

[default.build]
[default.build.parameters]
cached = true
parallel = true

[default.deploy]
[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
fail_on_empty_changeset = false
resolve_s3 = true
resolve_image_repos = true
parameter_overrides = "Environment=prod"

[prod]
[prod.global]
[prod.global.parameters]
stack_name = "echo-api-prod"
region = "ap-northeast-1"

[prod.build]
[prod.build.parameters]
cached = true
parallel = true

[prod.deploy]
[prod.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
fail_on_empty_changeset = false
resolve_s3 = true
resolve_image_repos = true
parameter_overrides = "Environment=prod"